### ISSUE TITLE
Cannot find module prompt_toolkit

### ISSUE THREAD

**Issue by Ainali** [dpriskorn/LexUtils#22]
**Describe the bug**
I run lexutils.py and get:

```
Traceback (most recent call last):
  File "/home/ainali/github/LexUtils/lexutils.py", line 3, in <module>
    from lexutils import main
  File "/home/ainali/github/LexUtils/lexutils/main.py", line 5, in <module>
    from prompt_toolkit import prompt
ModuleNotFoundError: No module named 'prompt_toolkit'
```

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Python 3.9.5

**Comment by dpriskorn** [comment]
I fixed the gettext issue in https://github.com/dpriskorn/LexUtils/commit/c0182a10635ab11422e8d5d80c7ee60ac090332a 
Please try to run `git pull & sudo pip install requirements.txt` and see if it solves the issue.

**Comment by Ainali** [comment]
> Please try to run `git pull & sudo pip install requirements.txt` and see if it solves the issue.

The second part gives this error message:

```
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt
```

Trying to run lexutils.py gives the same error message as in the original report.

**Comment by dpriskorn** [comment]
It is saying that it is trying to install the package "requirements.txt" which is clearly wrong.
The command above is missing "-r".
The official user guide has this command:
`python -m pip install -r requirements.txt`

**Comment by Ainali** [comment]
That made the install work fine! Now I instead get this error:

```
Traceback (most recent call last):
  File "/home/ainali/github/LexUtils/lexutils.py", line 3, in <module>
    from lexutils import main
  File "/home/ainali/github/LexUtils/lexutils/main.py", line 10, in <module>
    from fuzzyfinder import fuzzyfinder
ModuleNotFoundError: No module named 'fuzzyfinder'
```

**Comment by dpriskorn** [comment]
Thanks for the feedback. I fixed it in a commit just now. If you pull again it should work. :)

**Comment by Ainali** [comment]
Yes, that solved it!
